image: gitpod/workspace-java-17
 
tasks:
  - init: "docker-compose up -d"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - humao.rest-cliente
    - vscjava.vscode-glade
  ports
    visibility: private
